package Vista;
//@Autor Heber
import Base_de_Datos.Funciones_BD;
import Libreria.Cargar_Elementos;
import Libreria.Material;
import java.util.ArrayList;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.table.DefaultTableModel;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;


public class Busqueda_y_Clasficacion extends javax.swing.JFrame {

    public Busqueda_y_Clasficacion() {
        initComponents();
        Grupo_1.add(Boton_libro_eleccion_);
        Grupo_1.add(Boton_revista_eleccion_);
        Grupo_1.add(Boton_tesis_eleccion_);

        Grupo_2.add(boton_nombre_);
        Grupo_2.add(boton_autor_);
        Grupo_2.add(boton_palabraclave_);

        tabla_muestra_.setDefaultEditor(Object.class, null);
        cargarTabla();
        tabla_muestra_.getSelectionModel().addListSelectionListener(e -> {
            // Evitar eventos dobles
            if (!e.getValueIsAdjusting()) {
                filaSeleccionada();
            }
        });
        setLocationRelativeTo(null);

        //Disponibilidad_xd.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo_1 = new javax.swing.ButtonGroup();
        Grupo_2 = new javax.swing.ButtonGroup();
        Boton_atras_ = new javax.swing.JButton();
        titulo_text_ = new javax.swing.JLabel();
        filtrar_text_ = new javax.swing.JLabel();
        boton_nombre_ = new javax.swing.JRadioButton();
        boton_autor_ = new javax.swing.JRadioButton();
        boton_palabraclave_ = new javax.swing.JRadioButton();
        buscar_text_ = new javax.swing.JLabel();
        caja_buscar_ = new javax.swing.JTextField();
        boton_buscar_ = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_muestra_ = new javax.swing.JTable();
        titulo_agregar_text_ = new javax.swing.JLabel();
        autor_text_ = new javax.swing.JLabel();
        año_text = new javax.swing.JLabel();
        Caja_titulo_ = new javax.swing.JTextField();
        Descripcion_text_ = new javax.swing.JLabel();
        Caja_Autor_ = new javax.swing.JTextField();
        Caja_año_ = new javax.swing.JTextField();
        categoria_text_ = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Caja_descripcion_ = new javax.swing.JTextArea();
        Boton_libro_eleccion_ = new javax.swing.JRadioButton();
        Id_text_ = new javax.swing.JLabel();
        Boton_revista_eleccion_ = new javax.swing.JRadioButton();
        Boton_tesis_eleccion_ = new javax.swing.JRadioButton();
        extra1_ = new javax.swing.JLabel();
        extra2_ = new javax.swing.JLabel();
        Caja_1_ = new javax.swing.JTextField();
        Caja_2_ = new javax.swing.JTextField();
        Boton_guardar_ = new javax.swing.JButton();
        Id_intercambiable_txt_ = new javax.swing.JLabel();
        Boton_eleminar = new javax.swing.JButton();
        Disponibilidad_xd = new java.awt.Checkbox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Boton_atras_.setText("Atras");
        Boton_atras_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_atras_ActionPerformed(evt);
            }
        });

        titulo_text_.setText("Busqueda y CLasificacion");

        filtrar_text_.setText("Filtrar por:");

        boton_nombre_.setText("Titulo");

        boton_autor_.setText("Autor");

        boton_palabraclave_.setText("Palabra");
        boton_palabraclave_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_palabraclave_ActionPerformed(evt);
            }
        });

        buscar_text_.setText("Buscar");

        boton_buscar_.setText("Buscar");
        boton_buscar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_buscar_ActionPerformed(evt);
            }
        });

        tabla_muestra_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Autor", "Año"
            }
        ));
        jScrollPane1.setViewportView(tabla_muestra_);

        titulo_agregar_text_.setText("Nombre");

        autor_text_.setText("Autor");

        año_text.setText("Año");

        Caja_titulo_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Caja_titulo_ActionPerformed(evt);
            }
        });

        Descripcion_text_.setText("Descripcion");

        categoria_text_.setText("Categoria");

        Caja_descripcion_.setColumns(20);
        Caja_descripcion_.setRows(5);
        jScrollPane2.setViewportView(Caja_descripcion_);

        Boton_libro_eleccion_.setSelected(true);
        Boton_libro_eleccion_.setText("Libro Electronico");
        Boton_libro_eleccion_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_libro_eleccion_ActionPerformed(evt);
            }
        });

        Id_text_.setText("ID");

        Boton_revista_eleccion_.setText("Revista");
        Boton_revista_eleccion_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_revista_eleccion_ActionPerformed(evt);
            }
        });

        Boton_tesis_eleccion_.setText("Tesis");
        Boton_tesis_eleccion_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_tesis_eleccion_ActionPerformed(evt);
            }
        });

        extra1_.setText("--");

        extra2_.setText("--");

        Caja_1_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Caja_1_ActionPerformed(evt);
            }
        });

        Boton_guardar_.setText("Guardar");
        Boton_guardar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_guardar_ActionPerformed(evt);
            }
        });

        Id_intercambiable_txt_.setText("--");

        Boton_eleminar.setText("Eliminar");
        Boton_eleminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_eleminarActionPerformed(evt);
            }
        });

        Disponibilidad_xd.setLabel("Disponibilidad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filtrar_text_)
                            .addComponent(buscar_text_))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(caja_buscar_)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(boton_nombre_)
                                .addGap(41, 41, 41)
                                .addComponent(boton_autor_)
                                .addGap(69, 69, 69)
                                .addComponent(boton_palabraclave_)))
                        .addGap(42, 42, 42)
                        .addComponent(boton_buscar_))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(extra1_)
                                    .addComponent(extra2_)
                                    .addComponent(año_text)
                                    .addComponent(categoria_text_)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Id_text_)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Id_intercambiable_txt_))
                                        .addComponent(titulo_agregar_text_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(autor_text_))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Caja_1_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Caja_2_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Caja_año_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Caja_Autor_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Caja_titulo_, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Descripcion_text_)
                                                    .addComponent(Boton_guardar_, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Boton_eleminar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(Boton_libro_eleccion_)
                                        .addGap(18, 18, 18)
                                        .addComponent(Boton_revista_eleccion_, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(Boton_tesis_eleccion_, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(Disponibilidad_xd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Boton_atras_)
                        .addGap(131, 131, 131)
                        .addComponent(titulo_text_)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton_atras_)
                    .addComponent(titulo_text_, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filtrar_text_)
                    .addComponent(boton_nombre_)
                    .addComponent(boton_autor_)
                    .addComponent(boton_palabraclave_))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscar_text_)
                    .addComponent(caja_buscar_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_buscar_, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(categoria_text_)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Boton_libro_eleccion_)
                                    .addComponent(Boton_revista_eleccion_, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Boton_tesis_eleccion_))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Id_text_, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Id_intercambiable_txt_)
                            .addComponent(Descripcion_text_))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(titulo_agregar_text_, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Caja_titulo_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(autor_text_)
                                    .addComponent(Caja_Autor_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(año_text)
                                    .addComponent(Caja_año_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(extra1_)
                            .addComponent(Caja_1_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Caja_2_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(extra2_)
                            .addComponent(Boton_guardar_, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_eleminar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(Disponibilidad_xd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_atras_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_atras_ActionPerformed
        Menu_Principal nuevo = new Menu_Principal();
        nuevo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Boton_atras_ActionPerformed

    private void boton_buscar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_buscar_ActionPerformed
        Enumeration<AbstractButton> botones = Grupo_2.getElements();
        String filtro = "";
        while (botones.hasMoreElements()) {
            AbstractButton boton = botones.nextElement();
            if (boton.isSelected()) {
                filtro = boton.getText();
                break;
            }
        }

        String dato = caja_buscar_.getText();

        ArrayList<Material> resultados = Cargar_Elementos.buscar("xd", filtro, dato);

        cargarTablaConLista(resultados);
    }//GEN-LAST:event_boton_buscar_ActionPerformed

    private void Caja_titulo_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Caja_titulo_ActionPerformed

    }//GEN-LAST:event_Caja_titulo_ActionPerformed

    private void Boton_libro_eleccion_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_libro_eleccion_ActionPerformed
        extra1_.setText("Formato");
        extra2_.setText("Url de descarga");
    }//GEN-LAST:event_Boton_libro_eleccion_ActionPerformed

    private void Boton_revista_eleccion_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_revista_eleccion_ActionPerformed
        extra1_.setText("Categoria");
        extra2_.setText("Editor");
    }//GEN-LAST:event_Boton_revista_eleccion_ActionPerformed

    private void Boton_tesis_eleccion_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_tesis_eleccion_ActionPerformed
        extra1_.setText("Universidad");
        extra2_.setText("Asesor");
    }//GEN-LAST:event_Boton_tesis_eleccion_ActionPerformed

    private void Boton_guardar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_guardar_ActionPerformed
        // VALIDAR CAMPOS VACÍOS
        if (Id_intercambiable_txt_.getText().trim().isEmpty()
                || Caja_titulo_.getText().trim().isEmpty()
                || Caja_Autor_.getText().trim().isEmpty()
                || Caja_descripcion_.getText().trim().isEmpty()
                || Caja_año_.getText().trim().isEmpty()
                || Caja_1_.getText().trim().isEmpty()
                || Caja_2_.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Por favor completa todos los campos.",
                    "Campos vacíos",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // VALIDAR CLASIFICACIÓN
        Enumeration<AbstractButton> botones = Grupo_1.getElements();
        String Clasificacion = "";
        while (botones.hasMoreElements()) {
            AbstractButton boton = botones.nextElement();
            if (boton.isSelected()) {
                Clasificacion = boton.getText();
                break;
            }
        }

        if (Clasificacion.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Selecciona una clasificación.",
                    "Clasificación requerida",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // VALIDAR AÑO ENTERO
        int numeroAño;
        try {
            numeroAño = Integer.parseInt(Caja_año_.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "El año debe ser un número entero.",
                    "Año inválido",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // OBTENER DATOS
        String ids = Id_intercambiable_txt_.getText().trim();
        String Titulo = Caja_titulo_.getText().trim();
        String Autor = Caja_Autor_.getText().trim();
        String Descripcion = Caja_descripcion_.getText().trim();
        String waos1 = Caja_1_.getText().trim();
        String waos2 = Caja_2_.getText().trim();
        boolean estado = Disponibilidad_xd.getState();

        // ACTUALIZAR EN ARRAYLIST
        Boolean ok = Cargar_Elementos.actualizarMaterialPorId(
                ids,
                Titulo,
                Descripcion,
                Autor,
                String.valueOf(numeroAño),
                waos1,
                waos2,
                Clasificacion,
                estado
        );

        if (!ok) {
            JOptionPane.showMessageDialog(
                    this,
                    "No se encontró el material con ese ID.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // TEXTO PARA BD
        String estadoTxt = estado ? "Disponible" : "No disponible";

        // ACTUALIZAR EN BASE DE DATOS
        Funciones_BD dao = new Funciones_BD();
        String r = dao.Actualizar(
                ids,
                Titulo,
                Autor,
                Descripcion,
                numeroAño,
                waos1,
                waos2,
                Clasificacion,
                estadoTxt
        );

        JOptionPane.showMessageDialog(null, r);

        Funciones_BD actus = new Funciones_BD();
        actus.actu();
        cargarTabla();
    }//GEN-LAST:event_Boton_guardar_ActionPerformed

    private void boton_palabraclave_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_palabraclave_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_palabraclave_ActionPerformed

    private void Caja_1_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Caja_1_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Caja_1_ActionPerformed

    private void Boton_eleminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_eleminarActionPerformed
        String ide = Id_intercambiable_txt_.getText();
        Funciones_BD dao = new Funciones_BD();
        String respuesta = dao.eliminarMaterial(ide);
        JOptionPane.showMessageDialog(
                this,
                respuesta,
                "Aviso",
                JOptionPane.WARNING_MESSAGE
        );


    }//GEN-LAST:event_Boton_eleminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busqueda_y_Clasficacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busqueda_y_Clasficacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busqueda_y_Clasficacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busqueda_y_Clasficacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Busqueda_y_Clasficacion().setVisible(true);
            }
        });
    }

    private void cargarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tabla_muestra_.getModel();
        modelo.setRowCount(0); // Limpia la tabla

        for (Material m : Cargar_Elementos.materiales) {
            modelo.addRow(new Object[]{
                m.id,
                m.titulo,
                m.autor,
                m.anio
            });
        }
    }

    private void cargarTablaConLista(ArrayList<Material> lista) {
        DefaultTableModel modelo = (DefaultTableModel) tabla_muestra_.getModel();
        modelo.setRowCount(0); // Limpiar tabla

        for (Material m : lista) {
            modelo.addRow(new Object[]{
                m.id,
                m.titulo,
                m.autor,
                m.anio
            });
        }
    }

    private void filaSeleccionada() {
        int fila = tabla_muestra_.getSelectedRow();

        if (fila == -1) {
            return; // nada seleccionado
        }
        String id = tabla_muestra_.getValueAt(fila, 0).toString();
        String titulo = tabla_muestra_.getValueAt(fila, 1).toString();
        String autor = tabla_muestra_.getValueAt(fila, 2).toString();
        String anio = tabla_muestra_.getValueAt(fila, 3).toString();
        // Ejemplo: llenar cajas de texto
        Id_intercambiable_txt_.setText(id);
        Caja_titulo_.setText(titulo);
        Caja_Autor_.setText(autor);
        Caja_año_.setText(anio);

        Material waos = obtenerMaterialPorID(id);
        String descrip = waos.descripcion;
        String x1 = waos.extra1;
        String x2 = waos.extra2;
        Caja_1_.setText(x1);
        Caja_2_.setText(x2);
        Caja_descripcion_.setText(descrip);
        String cla = waos.cla;

        Disponibilidad_xd.setState(waos.disponibilidad);

        if (cla.equalsIgnoreCase("Tesis")) {
            Boton_tesis_eleccion_.setSelected(true);
            Boton_tesis_eleccion_.doClick();
            return;
        }
        if (cla.equalsIgnoreCase("Libro")) {
            Boton_libro_eleccion_.setSelected(true);
            Boton_libro_eleccion_.doClick();
            return;
        }
        if (cla.equalsIgnoreCase("Revista")) {
            Boton_revista_eleccion_.setSelected(true);
            Boton_revista_eleccion_.doClick();
            return;
        }

    }

    private Material obtenerMaterialPorID(String id) {
        return Cargar_Elementos.materiales.stream()
                .filter(m -> m.id.equalsIgnoreCase(id))
                .findFirst()
                .orElse(null);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_atras_;
    private javax.swing.JButton Boton_eleminar;
    private javax.swing.JButton Boton_guardar_;
    private javax.swing.JRadioButton Boton_libro_eleccion_;
    private javax.swing.JRadioButton Boton_revista_eleccion_;
    private javax.swing.JRadioButton Boton_tesis_eleccion_;
    private javax.swing.JTextField Caja_1_;
    private javax.swing.JTextField Caja_2_;
    private javax.swing.JTextField Caja_Autor_;
    private javax.swing.JTextField Caja_año_;
    private javax.swing.JTextArea Caja_descripcion_;
    private javax.swing.JTextField Caja_titulo_;
    private javax.swing.JLabel Descripcion_text_;
    private java.awt.Checkbox Disponibilidad_xd;
    private javax.swing.ButtonGroup Grupo_1;
    private javax.swing.ButtonGroup Grupo_2;
    private javax.swing.JLabel Id_intercambiable_txt_;
    private javax.swing.JLabel Id_text_;
    private javax.swing.JLabel autor_text_;
    private javax.swing.JLabel año_text;
    private javax.swing.JRadioButton boton_autor_;
    private javax.swing.JButton boton_buscar_;
    private javax.swing.JRadioButton boton_nombre_;
    private javax.swing.JRadioButton boton_palabraclave_;
    private javax.swing.JLabel buscar_text_;
    private javax.swing.JTextField caja_buscar_;
    private javax.swing.JLabel categoria_text_;
    private javax.swing.JLabel extra1_;
    private javax.swing.JLabel extra2_;
    private javax.swing.JLabel filtrar_text_;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla_muestra_;
    private javax.swing.JLabel titulo_agregar_text_;
    private javax.swing.JLabel titulo_text_;
    // End of variables declaration//GEN-END:variables
}
