package Vista;
//@Autor Heber
import Base_de_Datos.Funciones_BD;
import Interfaces.IPrestable;
import Libreria.*;
import java.util.ArrayList;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Gestion_de_Prestamos extends javax.swing.JFrame {


    public Gestion_de_Prestamos() {
        initComponents();
        Grupo_1.add(boton_libro_);
        Grupo_1.add(boton_revista_);
        Grupo_1.add(boton_tesis_);
        Grupo_1.add(boton_todo_);

        Grupo_2.add(boton_titulo_);
        Grupo_2.add(boton_autor_);
        Grupo_2.add(boton_palabra);

        boton_titulo_.setSelected(true);
        boton_todo_.setSelected(true);

        tabla_muestra_.setDefaultEditor(Object.class, null);
        cargarTabla();
        tabla_muestra_.getSelectionModel().addListSelectionListener(e -> {
            // Evitar eventos dobles
            if (!e.getValueIsAdjusting()) {
                filaSeleccionada();
            }
        });

        Disponibilidad_xd.setEnabled(false);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo_1 = new javax.swing.ButtonGroup();
        Grupo_2 = new javax.swing.ButtonGroup();
        Boton_atras_ = new javax.swing.JButton();
        titulo_bucar_txt_ = new javax.swing.JLabel();
        boton_titulo_ = new javax.swing.JRadioButton();
        boton_autor_ = new javax.swing.JRadioButton();
        boton_palabra = new javax.swing.JRadioButton();
        boton_buscar_ = new javax.swing.JButton();
        caja_buscar_ = new javax.swing.JTextField();
        Buscar_txt = new javax.swing.JLabel();
        clasificacion_txt_ = new javax.swing.JLabel();
        boton_tesis_ = new javax.swing.JRadioButton();
        boton_revista_ = new javax.swing.JRadioButton();
        boton_libro_ = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_muestra_ = new javax.swing.JTable();
        Autor = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        Año = new javax.swing.JLabel();
        caja_nombre_ = new javax.swing.JTextField();
        nombre_txt_ = new javax.swing.JLabel();
        edad_txt_ = new javax.swing.JLabel();
        usuario_txt = new javax.swing.JLabel();
        caja_edad_ = new javax.swing.JTextField();
        caja_dni_ = new javax.swing.JTextField();
        boton_realizar_ = new javax.swing.JButton();
        boton_todo_ = new javax.swing.JRadioButton();
        titulo_txt_libor = new javax.swing.JLabel();
        dni_txt_ = new javax.swing.JLabel();
        Disponibilidad_xd = new java.awt.Checkbox();
        ids_txt_ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Boton_atras_.setText("Atras");
        Boton_atras_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_atras_ActionPerformed(evt);
            }
        });

        titulo_bucar_txt_.setText("Buscar por:");

        boton_titulo_.setText("Titulo");

        boton_autor_.setText("Autor");

        boton_palabra.setText("Palabra");

        boton_buscar_.setText("Buscar");
        boton_buscar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_buscar_ActionPerformed(evt);
            }
        });

        Buscar_txt.setText("Buscar :");
        Buscar_txt.setToolTipText("");

        clasificacion_txt_.setText("Clasificacion:");

        boton_tesis_.setText("Tesis");

        boton_revista_.setText("Revista");

        boton_libro_.setText("Libro");

        tabla_muestra_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Titulo", "Autor", "Año"
            }
        ));
        jScrollPane1.setViewportView(tabla_muestra_);

        Autor.setText("---");

        Titulo.setText("---");

        Año.setText("---");

        nombre_txt_.setText("nombre");

        edad_txt_.setText("apellido");

        usuario_txt.setText("Usuario");
        usuario_txt.setToolTipText("");

        boton_realizar_.setText("Realizar Prestación");
        boton_realizar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_realizar_ActionPerformed(evt);
            }
        });

        boton_todo_.setText("Todas");

        titulo_txt_libor.setText("Libro");

        dni_txt_.setText("Dni");

        Disponibilidad_xd.setLabel("Disponibilidad");

        ids_txt_.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(titulo_txt_libor)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(ids_txt_))
                                            .addComponent(Disponibilidad_xd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 293, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(boton_realizar_))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(boton_tesis_)
                                                .addGap(54, 54, 54)
                                                .addComponent(boton_revista_))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(Autor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(Año, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(44, 44, 44)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(edad_txt_)
                                                    .addComponent(nombre_txt_)
                                                    .addComponent(dni_txt_))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(caja_dni_, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(caja_edad_, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(caja_nombre_, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(usuario_txt)
                                                        .addGap(83, 83, 83))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(boton_libro_)
                                                        .addGap(50, 50, 50))))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(boton_palabra)
                                        .addGap(132, 132, 132))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Boton_atras_))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(clasificacion_txt_)
                                        .addGap(31, 31, 31)
                                        .addComponent(boton_todo_))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addComponent(titulo_bucar_txt_)
                                        .addGap(44, 44, 44)
                                        .addComponent(boton_titulo_)
                                        .addGap(84, 84, 84)
                                        .addComponent(boton_autor_))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Buscar_txt)
                                        .addGap(26, 26, 26)
                                        .addComponent(caja_buscar_, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(boton_buscar_)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton_atras_)
                    .addComponent(titulo_bucar_txt_)
                    .addComponent(boton_titulo_)
                    .addComponent(boton_autor_)
                    .addComponent(boton_palabra))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buscar_txt)
                    .addComponent(caja_buscar_, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_buscar_, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clasificacion_txt_)
                        .addComponent(boton_todo_)
                        .addComponent(boton_tesis_)
                        .addComponent(boton_revista_))
                    .addComponent(boton_libro_, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ids_txt_)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(usuario_txt)
                                .addComponent(titulo_txt_libor)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre_txt_)
                            .addComponent(caja_nombre_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Titulo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edad_txt_)
                            .addComponent(caja_edad_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Autor))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caja_dni_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Año)
                            .addComponent(dni_txt_))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Disponibilidad_xd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(boton_realizar_)
                        .addGap(21, 21, 21))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_atras_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_atras_ActionPerformed
        Menu_Principal nuevo = new Menu_Principal();
        nuevo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Boton_atras_ActionPerformed

    private void boton_realizar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_realizar_ActionPerformed
        String id = ids_txt_.getText();
        Material mat = obtenerMaterialPorID(id);

        if (mat == null) {
            JOptionPane.showMessageDialog(null, "Material no encontrado.");
            return;
        }

        if (!(mat instanceof IPrestable)) {
            JOptionPane.showMessageDialog(null, "Este material NO se puede prestar.");
            return;
        }

// Datos del usuario
        String nombre = caja_nombre_.getText();
        String apellido = caja_edad_.getText();
        String dni = caja_dni_.getText();

// ----------------------
// VALIDACIÓN DE DATOS
// ----------------------
        nombre = nombre.trim();
        apellido = apellido.trim();
        dni = dni.trim();

        if (nombre.isEmpty() || apellido.isEmpty() || dni.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se permiten campos vacíos.");
            return;
        }

        if (!dni.matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "El DNI debe contener solo números.");
            return;
        }

        if (dni.length() != 8) {
            JOptionPane.showMessageDialog(null, "El DNI debe tener exactamente 8 dígitos.");
            return;
        }
// ----------------------

        IPrestable p = (IPrestable) mat;

// Intentar préstamo
        String resultado = p.prestar(nombre, apellido, dni);

        // ---------------------------
        //   MANEJAR RESULTADOS
        // ---------------------------
        // Usuario no encontrado
        if (resultado.equalsIgnoreCase("usuario no encontrado")) {

            int opcion = JOptionPane.showConfirmDialog(
                    null,
                    "El usuario no existe.\n¿Desea registrarlo?",
                    "Usuario no encontrado",
                    JOptionPane.YES_NO_OPTION
            );

            if (opcion == JOptionPane.YES_OPTION) {

                Funciones_BD dao = new Funciones_BD();
                String r = dao.InsertarUsuario(nombre, apellido, dni);

                if (r.equalsIgnoreCase("OK")) {
                    // Volver a intentar el préstamo
                    String r2 = p.prestar(nombre, apellido, dni);

                    if (r2.equalsIgnoreCase("OK")) {
                        JOptionPane.showMessageDialog(null, "Usuario registrado y préstamo exitoso.");
                    } else {
                        JOptionPane.showMessageDialog(null, "Usuario creado pero el préstamo falló: " + r2);
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo registrar el usuario.");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Operación cancelada.");
            }

            return;
        }

        // Préstamo exitoso
        if (resultado.equalsIgnoreCase("OK")) {
            JOptionPane.showMessageDialog(null, "Préstamo exitoso.");
            Funciones_BD actus = new Funciones_BD();
            actus.actu();
            cargarTabla();
            return;
        }

        // Cualquier otro error
        JOptionPane.showMessageDialog(null, "No se pudo realizar el préstamo: " + resultado);
       
    }//GEN-LAST:event_boton_realizar_ActionPerformed

    private void boton_buscar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_buscar_ActionPerformed

        Enumeration<AbstractButton> botones = Grupo_2.getElements();
        String filtro = "";
        while (botones.hasMoreElements()) {
            AbstractButton boton = botones.nextElement();
            if (boton.isSelected()) {
                filtro = boton.getText();
                break;
            }
        }

        Enumeration<AbstractButton> botones2 = Grupo_1.getElements();
        String filtro2 = "";
        while (botones2.hasMoreElements()) { // <-- usar botones2
            AbstractButton boton = botones2.nextElement(); // <-- usar botones2
            if (boton.isSelected()) {
                filtro2 = boton.getText();
                break;
            }
        }

        System.out.println("xd" + filtro);
        System.out.println("categoria :" + filtro2);
        String dato = caja_buscar_.getText();

        ArrayList<Material> resultados = Cargar_Elementos.buscar(filtro2, filtro, dato);

        cargarTablaConLista(resultados);
    }//GEN-LAST:event_boton_buscar_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_de_Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_de_Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_de_Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_de_Prestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion_de_Prestamos().setVisible(true);
            }
        });
    }

    private void cargarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tabla_muestra_.getModel();
        modelo.setRowCount(0); // Limpia la tabla

        for (Material m : Cargar_Elementos.materiales) {
            modelo.addRow(new Object[]{
                m.id,
                m.titulo,
                m.autor,
                m.anio
            });
        }
    }

    private void cargarTablaConLista(ArrayList<Material> lista) {
        DefaultTableModel modelo = (DefaultTableModel) tabla_muestra_.getModel();
        modelo.setRowCount(0); // Limpiar tabla

        for (Material m : lista) {
            modelo.addRow(new Object[]{
                m.id,
                m.titulo,
                m.autor,
                m.anio
            });
        }
    }

    private void filaSeleccionada() {
        int fila = tabla_muestra_.getSelectedRow();

        if (fila == -1) {
            return; // nada seleccionado
        }
        String id = tabla_muestra_.getValueAt(fila, 0).toString();
        String titulo = tabla_muestra_.getValueAt(fila, 1).toString();
        String autor = tabla_muestra_.getValueAt(fila, 2).toString();
        String anio = tabla_muestra_.getValueAt(fila, 3).toString();
        // Ejemplo: llenar cajas de texto
        Titulo.setText(titulo);
        Autor.setText(autor);
        Año.setText(anio);
        ids_txt_.setText(id);

        Material waos = obtenerMaterialPorID(id);
        String descrip = waos.descripcion;
        Disponibilidad_xd.setState(waos.disponibilidad);
        titulo_txt_libor.setText(waos.cla);
    }

    private Material obtenerMaterialPorID(String id) {
        return Cargar_Elementos.materiales.stream()
                .filter(m -> m.id.equalsIgnoreCase(id))
                .findFirst()
                .orElse(null);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Autor;
    private javax.swing.JLabel Año;
    private javax.swing.JButton Boton_atras_;
    private javax.swing.JLabel Buscar_txt;
    private java.awt.Checkbox Disponibilidad_xd;
    private javax.swing.ButtonGroup Grupo_1;
    private javax.swing.ButtonGroup Grupo_2;
    private javax.swing.JLabel Titulo;
    private javax.swing.JRadioButton boton_autor_;
    private javax.swing.JButton boton_buscar_;
    private javax.swing.JRadioButton boton_libro_;
    private javax.swing.JRadioButton boton_palabra;
    private javax.swing.JButton boton_realizar_;
    private javax.swing.JRadioButton boton_revista_;
    private javax.swing.JRadioButton boton_tesis_;
    private javax.swing.JRadioButton boton_titulo_;
    private javax.swing.JRadioButton boton_todo_;
    private javax.swing.JTextField caja_buscar_;
    private javax.swing.JTextField caja_dni_;
    private javax.swing.JTextField caja_edad_;
    private javax.swing.JTextField caja_nombre_;
    private javax.swing.JLabel clasificacion_txt_;
    private javax.swing.JLabel dni_txt_;
    private javax.swing.JLabel edad_txt_;
    private javax.swing.JLabel ids_txt_;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombre_txt_;
    private javax.swing.JTable tabla_muestra_;
    private javax.swing.JLabel titulo_bucar_txt_;
    private javax.swing.JLabel titulo_txt_libor;
    private javax.swing.JLabel usuario_txt;
    // End of variables declaration//GEN-END:variables
}
