package Vista;
//@Autor Heber
import Base_de_Datos.Funciones_BD;
import Libreria.Cargar_Elementos;
import Libreria.Material;
import Libreria.Usuario;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


public class Gestion_de_Devolucion extends javax.swing.JFrame {


    public Gestion_de_Devolucion() {
        initComponents();

        tabla_muestra_.setDefaultEditor(Object.class, null);
        cargarTablaPrestamos();
        tabla_muestra_.getSelectionModel().addListSelectionListener(e -> {
            // Evitar eventos dobles
            if (!e.getValueIsAdjusting()) {
                filaSeleccionada();
            }
        });
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_muestra_ = new javax.swing.JTable();
        boton_atras_ = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usuario_txt_ = new javax.swing.JLabel();
        libro_txt_ = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        caja_buscar_ = new javax.swing.JTextField();
        boton_buscar_ = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        id_txt_ = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ID_txt_ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla_muestra_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Libro", "Fecha Inicio", "Fecha Fin"
            }
        ));
        jScrollPane1.setViewportView(tabla_muestra_);

        boton_atras_.setText("Atras");
        boton_atras_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_atras_ActionPerformed(evt);
            }
        });

        jLabel1.setText("Usuario:");

        jLabel2.setText("Libro: ");

        usuario_txt_.setText("--");

        libro_txt_.setText("--");

        jButton1.setText("Devolver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        boton_buscar_.setText("Buscar");
        boton_buscar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_buscar_ActionPerformed(evt);
            }
        });

        jLabel5.setText("Buscar por ID:");

        id_txt_.setText("ID");

        jLabel7.setText("Devolver Material");

        ID_txt_.setText("--");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(470, 470, 470)
                                    .addComponent(jButton1)
                                    .addGap(15, 15, 15))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(442, 442, 442)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel1)
                                                .addComponent(id_txt_)))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(38, 38, 38)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(libro_txt_)
                                        .addComponent(usuario_txt_)
                                        .addComponent(ID_txt_))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel5)
                                .addGap(35, 35, 35)
                                .addComponent(caja_buscar_, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(boton_buscar_))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(boton_atras_)
                        .addGap(187, 187, 187)
                        .addComponent(jLabel7)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(ID_txt_)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usuario_txt_))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(libro_txt_))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_atras_)
                    .addComponent(jLabel7))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caja_buscar_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_buscar_)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(id_txt_)
                .addGap(216, 216, 216))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_atras_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_atras_ActionPerformed
        Menu_Principal nuevo = new Menu_Principal();
        nuevo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_atras_ActionPerformed

    private void boton_buscar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_buscar_ActionPerformed
        String palabra = caja_buscar_.getText();
        filtrarTablaPorID(palabra);

    }//GEN-LAST:event_boton_buscar_ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String id = ID_txt_.getText();
        Funciones_BD dao = new Funciones_BD();
        String xd = dao.DevolverMaterial(id);
        System.out.println(xd);

        Funciones_BD actus = new Funciones_BD();
        actus.actu();
        cargarTablaPrestamos();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_de_Devolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_de_Devolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_de_Devolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_de_Devolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion_de_Devolucion().setVisible(true);
            }
        });
    }

    private void cargarTablaPrestamos() {
        DefaultTableModel modelo = (DefaultTableModel) tabla_muestra_.getModel();
        modelo.setRowCount(0); // limpiar tabla

        for (String idPrestamo : Cargar_Elementos.prestamos.keySet()) {

            ArrayList<String> datos = Cargar_Elementos.prestamos.get(idPrestamo);

            if (datos == null || datos.size() < 4) {
                continue; // evitar errores
            }

            String idMaterial = datos.get(0);
            String idUsuario = datos.get(1);
            String fechaInicio = datos.get(2);
            String fechaFin = datos.get(3);

            // Buscar material por ID
            Material mat = obtenerMaterialPorID(idMaterial);
            String nombreLibro = (mat != null) ? mat.titulo : "Desconocido";

            // Buscar usuario por ID
            Usuario user = Cargar_Elementos.usuarios.get(idUsuario);
            String nombreUsuario = (user != null) ? (user.nombre + " " + user.apellido) : "Desconocido";

            // Cargar fila
            modelo.addRow(new Object[]{
                idPrestamo,
                nombreUsuario,
                nombreLibro,
                fechaInicio,
                fechaFin
            });
        }
    }

    private Material obtenerMaterialPorID(String id) {
        return Cargar_Elementos.materiales.stream()
                .filter(m -> m.id.equalsIgnoreCase(id))
                .findFirst()
                .orElse(null);
    }

    private void filaSeleccionada() {
        int fila = tabla_muestra_.getSelectedRow();
        if (fila == -1) {
            return;
        }
        String id = tabla_muestra_.getValueAt(fila, 0).toString();
        String nombre = tabla_muestra_.getValueAt(fila, 1).toString();
        String libro = tabla_muestra_.getValueAt(fila, 2).toString();

        ID_txt_.setText(id);
        usuario_txt_.setText(nombre);
        libro_txt_.setText(libro);

    }

    private void filtrarTablaPorID(String idBuscado) {
        if (idBuscado == null || idBuscado.trim().isEmpty()) {
            // Si no hay texto, cargar toda la tabla
            cargarTablaPrestamos();
            return;
        }

        DefaultTableModel modelo = (DefaultTableModel) tabla_muestra_.getModel();
        modelo.setRowCount(0); // Limpiar tabla

        // Recorrer todos los préstamos
        for (String idPrestamo : Cargar_Elementos.prestamos.keySet()) {
            // Solo mostrar los que coincidan con idBuscado (exacto o parcial)
            if (!idPrestamo.toLowerCase().contains(idBuscado.toLowerCase())) {
                continue;
            }

            ArrayList<String> datos = Cargar_Elementos.prestamos.get(idPrestamo);

            if (datos == null || datos.size() < 4) {
                continue;
            }

            String idMaterial = datos.get(0);
            String idUsuario = datos.get(1);
            String fechaInicio = datos.get(2);
            String fechaFin = datos.get(3);

            // Obtener nombre del material
            Material mat = obtenerMaterialPorID(idMaterial);
            String nombreMaterial = (mat != null) ? mat.titulo : "Desconocido";

            // Obtener nombre del usuario
            Usuario user = Cargar_Elementos.usuarios.get(idUsuario);
            String nombreUsuario = (user != null) ? (user.nombre + " " + user.apellido) : "Desconocido";

            // Agregar fila filtrada
            modelo.addRow(new Object[]{
                idPrestamo,
                nombreUsuario,
                nombreMaterial,
                fechaInicio,
                fechaFin
            });
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID_txt_;
    private javax.swing.JButton boton_atras_;
    private javax.swing.JButton boton_buscar_;
    private javax.swing.JTextField caja_buscar_;
    private javax.swing.JLabel id_txt_;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel libro_txt_;
    private javax.swing.JTable tabla_muestra_;
    private javax.swing.JLabel usuario_txt_;
    // End of variables declaration//GEN-END:variables
}
